use serde::{Deserialize, Serialize};
use sqlx::prelude::FromRow;

#[derive(Serialize, Deserialize, FromRow)]

pub struct ProjectView {
    pub id: i32,
    pub po_id: Option<String>,
    pub wo_id: Option<String>,
    pub project_type_id: Option<i16>,
    pub project_type: Option<String>, 
    pub region_id: Option<i32>,
    pub regional: Option<String>,   
    pub witel: Option<String>,  
    pub psa: Option<String>,         
    pub regional_id: Option<i32>,   
    pub witel_id: Option<i32>, 
    pub psa_id: Option<i32>,         
    pub unit: Option<String>,
    pub cable_volume: Option<i16>,
    pub pole: Option<i16>,
    pub port: Option<i16>,
    pub service_price: Option<i64>,
    pub material_price: Option<i64>,
    pub inc_material_price: Option<i64>,
    pub deploy_service_price: Option<i64>,
    pub description: Option<String>,
    pub attachment_path: Option<String>,
    pub service: Option<bool>,
    pub material: Option<bool>,
    pub status: Option<String>,
    pub phase: Option<String>,
    pub survey_md_doc: Option<String>,
    pub wo_doc: Option<String>,
    pub po_doc: Option<String>,
    pub pic: Option<String>,
    pub user_id: Option<i32>,
}

#[derive(Serialize, Deserialize)]
pub struct Project {
    pub id: i32,
    pub po_id: Option<String>,
    pub wo_id: Option<String>,
    pub project_type_id: Option<i16>,
    pub region_id: Option<i32>,
    pub unit: Option<String>,
    pub cable_volume: Option<i16>,
    pub pole: Option<i16>,
    pub port: Option<i16>,
    pub service_price: Option<i64>,
    pub material_price: Option<i64>,
    pub description: Option<String>,
    pub attachment_path: Option<String>,
    pub service: Option<bool>,
    pub material: Option<bool>,
    pub status: Option<String>,
}

#[derive(Serialize, Deserialize)]
pub struct GetListProjectByUser {
    pub id: i32,
    pub po_id: Option<String>,
    pub wo_id: Option<String>,
    pub project_type_id: Option<i16>,
    pub project_type: Option<String>, 
    pub region_id: Option<i32>,
    pub regional: Option<String>,   
    pub area: Option<String>,         
    pub witel: Option<String>,  
    pub regional_id: Option<i32>,   
    pub area_id: Option<i32>,         
    pub witel_id: Option<i32>, 
    pub unit: Option<String>,
    pub cable_volume: Option<i16>,
    pub pole: Option<i16>,
    pub port: Option<i16>,
    pub service_price: Option<i64>,
    pub material_price: Option<i64>,
    pub description: Option<String>,
    pub attachment_path: Option<String>,
    pub service: Option<bool>,
    pub material: Option<bool>,
    pub status: Option<String>,
}